package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Afp generated by hbm2java
 */
public class Afp  implements java.io.Serializable {


     private Integer codAfp;
     private String descripcion;
     private String minimo;
     private Set catPersonals = new HashSet(0);

    public Afp() {
    }

    public Afp(String descripcion, String minimo, Set catPersonals) {
       this.descripcion = descripcion;
       this.minimo = minimo;
       this.catPersonals = catPersonals;
    }
   
    public Integer getCodAfp() {
        return this.codAfp;
    }
    
    public void setCodAfp(Integer codAfp) {
        this.codAfp = codAfp;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(String minimo) {
        this.minimo = minimo;
    }
    public Set getCatPersonals() {
        return this.catPersonals;
    }
    
    public void setCatPersonals(Set catPersonals) {
        this.catPersonals = catPersonals;
    }




}


