package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * Autorizacion generated by hbm2java
 */
public class Autorizacion  implements java.io.Serializable {


     private Integer idautorizacion;
     private String descripcion;

    public Autorizacion() {
    }

    public Autorizacion(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getIdautorizacion() {
        return this.idautorizacion;
    }
    
    public void setIdautorizacion(Integer idautorizacion) {
        this.idautorizacion = idautorizacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


