package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bancos generated by hbm2java
 */
public class Bancos  implements java.io.Serializable {


     private Integer codBanco;
     private String descripcion;
     private Set catPersonals = new HashSet(0);

    public Bancos() {
    }

    public Bancos(String descripcion, Set catPersonals) {
       this.descripcion = descripcion;
       this.catPersonals = catPersonals;
    }
   
    public Integer getCodBanco() {
        return this.codBanco;
    }
    
    public void setCodBanco(Integer codBanco) {
        this.codBanco = codBanco;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCatPersonals() {
        return this.catPersonals;
    }
    
    public void setCatPersonals(Set catPersonals) {
        this.catPersonals = catPersonals;
    }




}


