package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private Integer codCargo;
     private String descripcion;
     private Set detalleMovimientoProgramacions = new HashSet(0);
     private Set catPersonals = new HashSet(0);

    public Cargos() {
    }

    public Cargos(String descripcion, Set detalleMovimientoProgramacions, Set catPersonals) {
       this.descripcion = descripcion;
       this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
       this.catPersonals = catPersonals;
    }
   
    public Integer getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(Integer codCargo) {
        this.codCargo = codCargo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetalleMovimientoProgramacions() {
        return this.detalleMovimientoProgramacions;
    }
    
    public void setDetalleMovimientoProgramacions(Set detalleMovimientoProgramacions) {
        this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
    }
    public Set getCatPersonals() {
        return this.catPersonals;
    }
    
    public void setCatPersonals(Set catPersonals) {
        this.catPersonals = catPersonals;
    }




}


