package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatPersonal generated by hbm2java
 */
public class CatPersonal  implements java.io.Serializable {


     private Integer codPersonal;
     private Afp afp;
     private Bancos bancos;
     private Cargos cargos;
     private Departamentos departamentos;
     private Programacion programacion;
     private String codJaryva;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String genero;
     private String estadoCivil;
     private String telefono1;
     private String telefono2;
     private Date fechaIngreso;
     private Date fechaNacimiento;
     private String dui;
     private String nit;
     private String isss;
     private String nup;
     private String ctaBancaria;
     private String catPago;
     private String obserbaciones;
     private Set contratoTrabajos = new HashSet(0);
     private Set detalleHojapagos = new HashSet(0);
     private Set detalleMovimientoProgramacions = new HashSet(0);
     private Set empDetalleactividadds = new HashSet(0);

    public CatPersonal() {
    }

    public CatPersonal(Afp afp, Bancos bancos, Cargos cargos, Departamentos departamentos, Programacion programacion, String codJaryva, String nombres, String apellidos, String direccion, String genero, String estadoCivil, String telefono1, String telefono2, Date fechaIngreso, Date fechaNacimiento, String dui, String nit, String isss, String nup, String ctaBancaria, String catPago, String obserbaciones, Set contratoTrabajos, Set detalleHojapagos, Set detalleMovimientoProgramacions, Set empDetalleactividadds) {
       this.afp = afp;
       this.bancos = bancos;
       this.cargos = cargos;
       this.departamentos = departamentos;
       this.programacion = programacion;
       this.codJaryva = codJaryva;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.fechaIngreso = fechaIngreso;
       this.fechaNacimiento = fechaNacimiento;
       this.dui = dui;
       this.nit = nit;
       this.isss = isss;
       this.nup = nup;
       this.ctaBancaria = ctaBancaria;
       this.catPago = catPago;
       this.obserbaciones = obserbaciones;
       this.contratoTrabajos = contratoTrabajos;
       this.detalleHojapagos = detalleHojapagos;
       this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
       this.empDetalleactividadds = empDetalleactividadds;
    }
   
    public Integer getCodPersonal() {
        return this.codPersonal;
    }
    
    public void setCodPersonal(Integer codPersonal) {
        this.codPersonal = codPersonal;
    }
    public Afp getAfp() {
        return this.afp;
    }
    
    public void setAfp(Afp afp) {
        this.afp = afp;
    }
    public Bancos getBancos() {
        return this.bancos;
    }
    
    public void setBancos(Bancos bancos) {
        this.bancos = bancos;
    }
    public Cargos getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Cargos cargos) {
        this.cargos = cargos;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Programacion getProgramacion() {
        return this.programacion;
    }
    
    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }
    public String getCodJaryva() {
        return this.codJaryva;
    }
    
    public void setCodJaryva(String codJaryva) {
        this.codJaryva = codJaryva;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getIsss() {
        return this.isss;
    }
    
    public void setIsss(String isss) {
        this.isss = isss;
    }
    public String getNup() {
        return this.nup;
    }
    
    public void setNup(String nup) {
        this.nup = nup;
    }
    public String getCtaBancaria() {
        return this.ctaBancaria;
    }
    
    public void setCtaBancaria(String ctaBancaria) {
        this.ctaBancaria = ctaBancaria;
    }
    public String getCatPago() {
        return this.catPago;
    }
    
    public void setCatPago(String catPago) {
        this.catPago = catPago;
    }
    public String getObserbaciones() {
        return this.obserbaciones;
    }
    
    public void setObserbaciones(String obserbaciones) {
        this.obserbaciones = obserbaciones;
    }
    public Set getContratoTrabajos() {
        return this.contratoTrabajos;
    }
    
    public void setContratoTrabajos(Set contratoTrabajos) {
        this.contratoTrabajos = contratoTrabajos;
    }
    public Set getDetalleHojapagos() {
        return this.detalleHojapagos;
    }
    
    public void setDetalleHojapagos(Set detalleHojapagos) {
        this.detalleHojapagos = detalleHojapagos;
    }
    public Set getDetalleMovimientoProgramacions() {
        return this.detalleMovimientoProgramacions;
    }
    
    public void setDetalleMovimientoProgramacions(Set detalleMovimientoProgramacions) {
        this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
    }
    public Set getEmpDetalleactividadds() {
        return this.empDetalleactividadds;
    }
    
    public void setEmpDetalleactividadds(Set empDetalleactividadds) {
        this.empDetalleactividadds = empDetalleactividadds;
    }




}


