package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContratoTrabajo generated by hbm2java
 */
public class ContratoTrabajo  implements java.io.Serializable {


     private Integer idcontrato;
     private CatPersonal catPersonal;
     private Date fechacontrato;
     private Date finalizacioncontrato;
     private Date enfecha;
     private String extendido;
     private String nacionalidad;
     private String profesion;
     private String lugartrabajo;
     private Set grupofamiliars = new HashSet(0);
     private Set obligacionesContratos = new HashSet(0);
     private Set devengosContratos = new HashSet(0);

    public ContratoTrabajo() {
    }

	
    public ContratoTrabajo(CatPersonal catPersonal, Date fechacontrato, Date finalizacioncontrato, Date enfecha, String extendido, String nacionalidad, String profesion, String lugartrabajo) {
        this.catPersonal = catPersonal;
        this.fechacontrato = fechacontrato;
        this.finalizacioncontrato = finalizacioncontrato;
        this.enfecha = enfecha;
        this.extendido = extendido;
        this.nacionalidad = nacionalidad;
        this.profesion = profesion;
        this.lugartrabajo = lugartrabajo;
    }
    public ContratoTrabajo(CatPersonal catPersonal, Date fechacontrato, Date finalizacioncontrato, Date enfecha, String extendido, String nacionalidad, String profesion, String lugartrabajo, Set grupofamiliars, Set obligacionesContratos, Set devengosContratos) {
       this.catPersonal = catPersonal;
       this.fechacontrato = fechacontrato;
       this.finalizacioncontrato = finalizacioncontrato;
       this.enfecha = enfecha;
       this.extendido = extendido;
       this.nacionalidad = nacionalidad;
       this.profesion = profesion;
       this.lugartrabajo = lugartrabajo;
       this.grupofamiliars = grupofamiliars;
       this.obligacionesContratos = obligacionesContratos;
       this.devengosContratos = devengosContratos;
    }
   
    public Integer getIdcontrato() {
        return this.idcontrato;
    }
    
    public void setIdcontrato(Integer idcontrato) {
        this.idcontrato = idcontrato;
    }
    public CatPersonal getCatPersonal() {
        return this.catPersonal;
    }
    
    public void setCatPersonal(CatPersonal catPersonal) {
        this.catPersonal = catPersonal;
    }
    public Date getFechacontrato() {
        return this.fechacontrato;
    }
    
    public void setFechacontrato(Date fechacontrato) {
        this.fechacontrato = fechacontrato;
    }
    public Date getFinalizacioncontrato() {
        return this.finalizacioncontrato;
    }
    
    public void setFinalizacioncontrato(Date finalizacioncontrato) {
        this.finalizacioncontrato = finalizacioncontrato;
    }
    public Date getEnfecha() {
        return this.enfecha;
    }
    
    public void setEnfecha(Date enfecha) {
        this.enfecha = enfecha;
    }
    public String getExtendido() {
        return this.extendido;
    }
    
    public void setExtendido(String extendido) {
        this.extendido = extendido;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getLugartrabajo() {
        return this.lugartrabajo;
    }
    
    public void setLugartrabajo(String lugartrabajo) {
        this.lugartrabajo = lugartrabajo;
    }
    public Set getGrupofamiliars() {
        return this.grupofamiliars;
    }
    
    public void setGrupofamiliars(Set grupofamiliars) {
        this.grupofamiliars = grupofamiliars;
    }
    public Set getObligacionesContratos() {
        return this.obligacionesContratos;
    }
    
    public void setObligacionesContratos(Set obligacionesContratos) {
        this.obligacionesContratos = obligacionesContratos;
    }
    public Set getDevengosContratos() {
        return this.devengosContratos;
    }
    
    public void setDevengosContratos(Set devengosContratos) {
        this.devengosContratos = devengosContratos;
    }




}


