package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer codDepartamento;
     private String descripcion;
     private Set catPersonals = new HashSet(0);

    public Departamentos() {
    }

    public Departamentos(String descripcion, Set catPersonals) {
       this.descripcion = descripcion;
       this.catPersonals = catPersonals;
    }
   
    public Integer getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(Integer codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCatPersonals() {
        return this.catPersonals;
    }
    
    public void setCatPersonals(Set catPersonals) {
        this.catPersonals = catPersonals;
    }




}


