package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * DetalleHojapago generated by hbm2java
 */
public class DetalleHojapago  implements java.io.Serializable {


     private Integer iddetalleHoja;
     private CatPersonal catPersonal;
     private Hojapago hojapago;
     private String prg;
     private String trabajo;
     private String descripcion;

    public DetalleHojapago() {
    }

    public DetalleHojapago(CatPersonal catPersonal, Hojapago hojapago, String prg, String trabajo, String descripcion) {
       this.catPersonal = catPersonal;
       this.hojapago = hojapago;
       this.prg = prg;
       this.trabajo = trabajo;
       this.descripcion = descripcion;
    }
   
    public Integer getIddetalleHoja() {
        return this.iddetalleHoja;
    }
    
    public void setIddetalleHoja(Integer iddetalleHoja) {
        this.iddetalleHoja = iddetalleHoja;
    }
    public CatPersonal getCatPersonal() {
        return this.catPersonal;
    }
    
    public void setCatPersonal(CatPersonal catPersonal) {
        this.catPersonal = catPersonal;
    }
    public Hojapago getHojapago() {
        return this.hojapago;
    }
    
    public void setHojapago(Hojapago hojapago) {
        this.hojapago = hojapago;
    }
    public String getPrg() {
        return this.prg;
    }
    
    public void setPrg(String prg) {
        this.prg = prg;
    }
    public String getTrabajo() {
        return this.trabajo;
    }
    
    public void setTrabajo(String trabajo) {
        this.trabajo = trabajo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


