package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleMovimientoProgramacion generated by hbm2java
 */
public class DetalleMovimientoProgramacion  implements java.io.Serializable {


     private Integer id;
     private Cargos cargos;
     private CatPersonal catPersonal;
     private Movimientoprogramacion movimientoprogramacion;
     private Date fecha;
     private double horas;
     private BigDecimal precio;
     private BigDecimal valor;

    public DetalleMovimientoProgramacion() {
    }

    public DetalleMovimientoProgramacion(Cargos cargos, CatPersonal catPersonal, Movimientoprogramacion movimientoprogramacion, Date fecha, double horas, BigDecimal precio, BigDecimal valor) {
       this.cargos = cargos;
       this.catPersonal = catPersonal;
       this.movimientoprogramacion = movimientoprogramacion;
       this.fecha = fecha;
       this.horas = horas;
       this.precio = precio;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cargos getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Cargos cargos) {
        this.cargos = cargos;
    }
    public CatPersonal getCatPersonal() {
        return this.catPersonal;
    }
    
    public void setCatPersonal(CatPersonal catPersonal) {
        this.catPersonal = catPersonal;
    }
    public Movimientoprogramacion getMovimientoprogramacion() {
        return this.movimientoprogramacion;
    }
    
    public void setMovimientoprogramacion(Movimientoprogramacion movimientoprogramacion) {
        this.movimientoprogramacion = movimientoprogramacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getHoras() {
        return this.horas;
    }
    
    public void setHoras(double horas) {
        this.horas = horas;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


