package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * EmpDetalleactividadd generated by hbm2java
 */
public class EmpDetalleactividadd  implements java.io.Serializable {


     private Integer id;
     private CatPersonal catPersonal;
     private String pag;
     private int guia;

    public EmpDetalleactividadd() {
    }

    public EmpDetalleactividadd(CatPersonal catPersonal, String pag, int guia) {
       this.catPersonal = catPersonal;
       this.pag = pag;
       this.guia = guia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CatPersonal getCatPersonal() {
        return this.catPersonal;
    }
    
    public void setCatPersonal(CatPersonal catPersonal) {
        this.catPersonal = catPersonal;
    }
    public String getPag() {
        return this.pag;
    }
    
    public void setPag(String pag) {
        this.pag = pag;
    }
    public int getGuia() {
        return this.guia;
    }
    
    public void setGuia(int guia) {
        this.guia = guia;
    }




}


