package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * EmpUniondetalleactividad generated by hbm2java
 */
public class EmpUniondetalleactividad  implements java.io.Serializable {


     private int id;
     private int idempleadoDetalleactividad;
     private int iddetalleActpro;

    public EmpUniondetalleactividad() {
    }

    public EmpUniondetalleactividad(int id, int idempleadoDetalleactividad, int iddetalleActpro) {
       this.id = id;
       this.idempleadoDetalleactividad = idempleadoDetalleactividad;
       this.iddetalleActpro = iddetalleActpro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdempleadoDetalleactividad() {
        return this.idempleadoDetalleactividad;
    }
    
    public void setIdempleadoDetalleactividad(int idempleadoDetalleactividad) {
        this.idempleadoDetalleactividad = idempleadoDetalleactividad;
    }
    public int getIddetalleActpro() {
        return this.iddetalleActpro;
    }
    
    public void setIddetalleActpro(int iddetalleActpro) {
        this.iddetalleActpro = iddetalleActpro;
    }




}


