package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * Grupofamiliar generated by hbm2java
 */
public class Grupofamiliar  implements java.io.Serializable {


     private Integer idgrupo;
     private ContratoTrabajo contratoTrabajo;
     private String grupofamiliar;
     private String parentezco;

    public Grupofamiliar() {
    }

    public Grupofamiliar(ContratoTrabajo contratoTrabajo, String grupofamiliar, String parentezco) {
       this.contratoTrabajo = contratoTrabajo;
       this.grupofamiliar = grupofamiliar;
       this.parentezco = parentezco;
    }
   
    public Integer getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(Integer idgrupo) {
        this.idgrupo = idgrupo;
    }
    public ContratoTrabajo getContratoTrabajo() {
        return this.contratoTrabajo;
    }
    
    public void setContratoTrabajo(ContratoTrabajo contratoTrabajo) {
        this.contratoTrabajo = contratoTrabajo;
    }
    public String getGrupofamiliar() {
        return this.grupofamiliar;
    }
    
    public void setGrupofamiliar(String grupofamiliar) {
        this.grupofamiliar = grupofamiliar;
    }
    public String getParentezco() {
        return this.parentezco;
    }
    
    public void setParentezco(String parentezco) {
        this.parentezco = parentezco;
    }




}


