package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Movimientoprogramacion generated by hbm2java
 */
public class Movimientoprogramacion  implements java.io.Serializable {


     private Integer id;
     private Planillas planillas;
     private Set programacioneses = new HashSet(0);
     private Set detalleMovimientoProgramacions = new HashSet(0);

    public Movimientoprogramacion() {
    }

	
    public Movimientoprogramacion(Planillas planillas) {
        this.planillas = planillas;
    }
    public Movimientoprogramacion(Planillas planillas, Set programacioneses, Set detalleMovimientoProgramacions) {
       this.planillas = planillas;
       this.programacioneses = programacioneses;
       this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Planillas getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Planillas planillas) {
        this.planillas = planillas;
    }
    public Set getProgramacioneses() {
        return this.programacioneses;
    }
    
    public void setProgramacioneses(Set programacioneses) {
        this.programacioneses = programacioneses;
    }
    public Set getDetalleMovimientoProgramacions() {
        return this.detalleMovimientoProgramacions;
    }
    
    public void setDetalleMovimientoProgramacions(Set detalleMovimientoProgramacions) {
        this.detalleMovimientoProgramacions = detalleMovimientoProgramacions;
    }




}


