package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * ObligacionesContrato generated by hbm2java
 */
public class ObligacionesContrato  implements java.io.Serializable {


     private Integer idobligaciones;
     private ContratoTrabajo contratoTrabajo;
     private String obligaciones;

    public ObligacionesContrato() {
    }

    public ObligacionesContrato(ContratoTrabajo contratoTrabajo, String obligaciones) {
       this.contratoTrabajo = contratoTrabajo;
       this.obligaciones = obligaciones;
    }
   
    public Integer getIdobligaciones() {
        return this.idobligaciones;
    }
    
    public void setIdobligaciones(Integer idobligaciones) {
        this.idobligaciones = idobligaciones;
    }
    public ContratoTrabajo getContratoTrabajo() {
        return this.contratoTrabajo;
    }
    
    public void setContratoTrabajo(ContratoTrabajo contratoTrabajo) {
        this.contratoTrabajo = contratoTrabajo;
    }
    public String getObligaciones() {
        return this.obligaciones;
    }
    
    public void setObligaciones(String obligaciones) {
        this.obligaciones = obligaciones;
    }




}


