package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Planillas generated by hbm2java
 */
public class Planillas  implements java.io.Serializable {


     private String codigoplanilla;
     private Date desde;
     private Date hasta;
     private String status;
     private Set movimientoprogramacions = new HashSet(0);
     private Set programacioneses = new HashSet(0);

    public Planillas() {
    }

	
    public Planillas(String codigoplanilla, Date desde, Date hasta, String status) {
        this.codigoplanilla = codigoplanilla;
        this.desde = desde;
        this.hasta = hasta;
        this.status = status;
    }
    public Planillas(String codigoplanilla, Date desde, Date hasta, String status, Set movimientoprogramacions, Set programacioneses) {
       this.codigoplanilla = codigoplanilla;
       this.desde = desde;
       this.hasta = hasta;
       this.status = status;
       this.movimientoprogramacions = movimientoprogramacions;
       this.programacioneses = programacioneses;
    }
   
    public String getCodigoplanilla() {
        return this.codigoplanilla;
    }
    
    public void setCodigoplanilla(String codigoplanilla) {
        this.codigoplanilla = codigoplanilla;
    }
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getMovimientoprogramacions() {
        return this.movimientoprogramacions;
    }
    
    public void setMovimientoprogramacions(Set movimientoprogramacions) {
        this.movimientoprogramacions = movimientoprogramacions;
    }
    public Set getProgramacioneses() {
        return this.programacioneses;
    }
    
    public void setProgramacioneses(Set programacioneses) {
        this.programacioneses = programacioneses;
    }




}


