package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programacion generated by hbm2java
 */
public class Programacion  implements java.io.Serializable {


     private Integer codProgramacion;
     private String descripcion;
     private Set programacioneses = new HashSet(0);
     private Set catPersonals = new HashSet(0);
     private Set eventoses = new HashSet(0);

    public Programacion() {
    }

    public Programacion(String descripcion, Set programacioneses, Set catPersonals, Set eventoses) {
       this.descripcion = descripcion;
       this.programacioneses = programacioneses;
       this.catPersonals = catPersonals;
       this.eventoses = eventoses;
    }
   
    public Integer getCodProgramacion() {
        return this.codProgramacion;
    }
    
    public void setCodProgramacion(Integer codProgramacion) {
        this.codProgramacion = codProgramacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProgramacioneses() {
        return this.programacioneses;
    }
    
    public void setProgramacioneses(Set programacioneses) {
        this.programacioneses = programacioneses;
    }
    public Set getCatPersonals() {
        return this.catPersonals;
    }
    
    public void setCatPersonals(Set catPersonals) {
        this.catPersonals = catPersonals;
    }
    public Set getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set eventoses) {
        this.eventoses = eventoses;
    }




}


