package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salones generated by hbm2java
 */
public class Salones  implements java.io.Serializable {


     private Integer idsalon;
     private String descripcion;
     private Set programacioneses = new HashSet(0);

    public Salones() {
    }

    public Salones(String descripcion, Set programacioneses) {
       this.descripcion = descripcion;
       this.programacioneses = programacioneses;
    }
   
    public Integer getIdsalon() {
        return this.idsalon;
    }
    
    public void setIdsalon(Integer idsalon) {
        this.idsalon = idsalon;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProgramacioneses() {
        return this.programacioneses;
    }
    
    public void setProgramacioneses(Set programacioneses) {
        this.programacioneses = programacioneses;
    }




}


