package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TipoPlanilla generated by hbm2java
 */
public class TipoPlanilla  implements java.io.Serializable {


     private Integer codTipoplanilla;
     private String descripcion;
     private BigDecimal precio;

    public TipoPlanilla() {
    }

    public TipoPlanilla(String descripcion, BigDecimal precio) {
       this.descripcion = descripcion;
       this.precio = precio;
    }
   
    public Integer getCodTipoplanilla() {
        return this.codTipoplanilla;
    }
    
    public void setCodTipoplanilla(Integer codTipoplanilla) {
        this.codTipoplanilla = codTipoplanilla;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


