package entities;
// Generated 10-24-2019 05:29:51 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private String usuario;
     private String nivelAcceso;
     private String clave;

    public Usuarios() {
    }

    public Usuarios(String nombre, String usuario, String nivelAcceso, String clave) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.nivelAcceso = nivelAcceso;
       this.clave = clave;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNivelAcceso() {
        return this.nivelAcceso;
    }
    
    public void setNivelAcceso(String nivelAcceso) {
        this.nivelAcceso = nivelAcceso;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


